version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - npm run test:all || true
      - npm run report
      - zip -r reports.zip reports

artifacts:
  files:
    - reports/**/*
  discard-paths: no
