version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - npm run ci
      - zip -r reports.zip reports

artifacts:
  files:
    - reports/**/*
    - reports.zip
  discard-paths: no

reports:
  cucumber-test-report:
    files:
      - reports/json/merged/merged.json # ← CodeBuildがここを読んでレポート化
    file-format: CUCUMBERJSON
